---
title: "get_GDD"
output: html_document
date: "2025-06-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
```


# Import files
```{r}
temps2020 <- read.csv('temps_2020.csv', skip = 10)
temps2021 <- read.csv('temps_2021.csv', skip = 10)
temps2022 <- read.csv('temps_2022.csv', skip = 10)
temps2023 <- read.csv('temps_2023.csv', skip = 10)
temps2024 <- read.csv('temps_2024.csv', skip = 10)

# Get dates
temps2020$date <- as.Date(temps2020$DOY - 1, origin = paste0(as.character(temps2020$YEAR[1]), "-01-01"))
temps2021$date <- as.Date(temps2021$DOY - 1, origin = paste0(as.character(temps2021$YEAR[1]), "-01-01"))
temps2022$date <- as.Date(temps2022$DOY - 1, origin = paste0(as.character(temps2022$YEAR[1]), "-01-01"))
temps2023$date <- as.Date(temps2023$DOY - 1, origin = paste0(as.character(temps2023$YEAR[1]), "-01-01"))
temps2024$date <- as.Date(temps2024$DOY - 1, origin = paste0(as.character(temps2024$YEAR[1]), "-01-01"))

# Get planting dates
planting_date2020 <- as.Date("2020-05-22")
planting_date2021 <- as.Date("2021-05-20")
planting_date2022 <- as.Date("2022-05-12")
planting_date2023 <- as.Date("2023-05-12")
planting_date2024 <- as.Date("2024-05-20")
```


```{r}
# Set base and cap temperatures
T_base <- 50
T_cap <- 86

# Convert temps to Fahrenheit
temps2020$max_F = temps2020$T2M_MAX * 9/5 + 32
temps2020$min_F = temps2020$T2M_MIN * 9/5 + 32

temps2021$max_F = temps2021$T2M_MAX * 9/5 + 32
temps2021$min_F = temps2021$T2M_MIN * 9/5 + 32

temps2022$max_F = temps2022$T2M_MAX * 9/5 + 32
temps2022$min_F = temps2022$T2M_MIN * 9/5 + 32

temps2023$max_F = temps2023$T2M_MAX * 9/5 + 32
temps2023$min_F = temps2023$T2M_MIN * 9/5 + 32

temps2024$max_F = temps2024$T2M_MAX * 9/5 + 32
temps2024$min_F = temps2024$T2M_MIN * 9/5 + 32
```


# Get GDD
```{r}
# Filter from planting date onward
gdd2020 <- temps2020 %>%
  filter(date > planting_date2020) %>% #begin gdd and gdd_sum the day after planting
  mutate(
    tmax_adj = pmin(max_F, T_cap), #if max temp is greater than 86, set max to 86
    tmin_adj = pmax(min_F, T_base), #if min temp is less than 50, set min to 50
    gdd = pmax(0, (tmax_adj + tmin_adj)/2 - T_base),
    cumulative_gdd = cumsum(gdd)
  )

gdd2021 <- temps2021 %>%
  filter(date > planting_date2021) %>% #begin gdd and gdd_sum the day after planting
  mutate(
    tmax_adj = pmin(max_F, T_cap), #if max temp is greater than 86, set max to 86
    tmin_adj = pmax(min_F, T_base), #if min temp is less than 50, set min to 50
    gdd = pmax(0, (tmax_adj + tmin_adj)/2 - T_base),
    cumulative_gdd = cumsum(gdd)
  )

gdd2022 <- temps2022 %>%
  filter(date > planting_date2022) %>% #begin gdd and gdd_sum the day after planting
  mutate(
    tmax_adj = pmin(max_F, T_cap), #if max temp is greater than 86, set max to 86
    tmin_adj = pmax(min_F, T_base), #if min temp is less than 50, set min to 50
    gdd = pmax(0, (tmax_adj + tmin_adj)/2 - T_base),
    cumulative_gdd = cumsum(gdd)
  )

gdd2023 <- temps2023 %>%
  filter(date > planting_date2023) %>% #begin gdd and gdd_sum the day after planting
  mutate(
    tmax_adj = pmin(max_F, T_cap), #if max temp is greater than 86, set max to 86
    tmin_adj = pmax(min_F, T_base), #if min temp is less than 50, set min to 50
    gdd = pmax(0, (tmax_adj + tmin_adj)/2 - T_base),
    cumulative_gdd = cumsum(gdd)
  )

gdd2024 <- temps2024 %>%
  filter(date > planting_date2024) %>% #begin gdd and gdd_sum the day after planting
  mutate(
    tmax_adj = pmin(max_F, T_cap), #if max temp is greater than 86, set max to 86
    tmin_adj = pmax(min_F, T_base), #if min temp is less than 50, set min to 50
    gdd = pmax(0, (tmax_adj + tmin_adj)/2 - T_base),
    cumulative_gdd = cumsum(gdd)
  )

gdd_all <- rbind(gdd2020, gdd2021, gdd2022, gdd2023, gdd2024)
```


# Save files
```{r}
write.csv(gdd_all, "gdd_2020-24.csv")
```


