---
title: "get_lidar_md"
output: pdf_document
date: "2024-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
setwd("/Users/eef52/Documents/Cornell/UAV-UGV/LSP_Analysis/get_labels/lidar_labels")
```


#Import libraries
```{r}
library(tidyverse)
library(dplyr)
library(stringr)
```


#Import files
```{r}
#Get lidar filenames
filenames <- read.csv("lidar_filenames_NYH2_NYH3_2020-24.csv") #border ranges and bad pc plots removed

#Get plot splits
ps_all <- read.csv("PlotSplits_NYH2_NYH3_2020-24.csv")

#Get G2F field information
md2020 = read_csv("https://de.cyverse.org/anon-files/iplant/home/shared/commons_repo/curated/GenomesToFields_G2F_data_2020/a._2020_phenotypic_data/g2f_2020_phenotypic_clean_data.csv")
md2021 = read_csv("https://de.cyverse.org/anon-files/iplant/home/shared/commons_repo/curated/GenomesToFields_G2F_data_2021/a._2021_phenotypic_data/g2f_2021_phenotypic_clean_data.csv")
md2022 = read_csv("https://de.cyverse.org/anon-files/iplant/home/shared/commons_repo/curated/GenomesToFields_G2F_data_2022/a._2022_phenotypic_data/g2f_2022_phenotypic_clean_data.csv")
md2023 = read.csv("G2F_2023/G2F_2023_modified.csv", check.names = FALSE)
md2024 = read.csv("G2F_2024/G2F_2024_modified.csv", check.names = FALSE)

#Filter
md2020 <- md2020[md2020$`Field-Location` %in% c('NYH2', 'NYH3'), c("Year", "Field-Location","Plot", "Pass", "Range")]
md2021 <- md2021[md2021$`Field-Location` %in% c('NYH2', 'NYH3'), c("Year", "Field-Location","Plot", "Pass", "Range")]
md2022 <- md2022[md2022$`Field-Location` %in% c('NYH2', 'NYH3'), c("Year", "Field-Location","Plot", "Pass", "Range")]
md2023 <- md2023[md2023$`Field-Location` %in% c('NYH2', 'NYH3'), c("Year", "Field-Location","Plot", "Pass", "Range")]
md2024 <- md2024[md2024$`Field-Location` %in% c('NYH2', 'NYH3'), c("Year", "Field-Location","Plot", "Pass", "Range")]

#Create single df
md_all <- rbind(md2020, md2021, md2022, md2023, md2024)
colnames(md_all) <- c('year', 'field', 'plot', 'column', 'range')
md_all$column <- as.integer(md_all$column)
md_all$plot <- as.integer(md_all$plot)
```


#Add metadata from plot splits and G2F field information
```{r}
#Add field and column number
md <- filenames %>% 
  left_join(ps_all, by = join_by(collection, range))

#Add plot number
md <- md %>% 
  left_join(md_all, by = join_by(year, field, column, range))
```


#Remove other fields, border rows, and duplicates
```{r}
#Remove other fields & border rows, if needed
md <- md[!is.na(md$plot), ]

#Remove duplicates
md <- md %>%
  arrange(date, column, desc(range)) %>%
  distinct(date, column, range, .keep_all = TRUE)

#Look at data
table(md$date)
```


#Save files
```{r}
write.csv(md, file = 'lidar_md_NYH2_NYH3_2020-24.csv', quote = FALSE)
```


